Operations to perform:
  Apply all migrations: accounts, admin, auth, clients, contenttypes, property, reservation, sessions
Running migrations:
  No migrations to apply.
  Your models in app(s): 'clients', 'property', 'reservation' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Watching for file changes with StatReloader
INFO 2025-08-15 15:43:53,404 autoreload 5390 140579025296576 Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 15, 2025 - 15:43:53
Django version 4.2.11, using settings 'config.settings'
Starting development server at http://0.0.0.0:5000/
Quit the server with CONTROL-C.

Invalid HTTP_HOST header: 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev'. You may need to add 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev'. You may need to add 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev' to ALLOWED_HOSTS.
ERROR 2025-08-15 15:43:54,644 exception 5390 140578927056576 Invalid HTTP_HOST header: 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev'. You may need to add 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev'. You may need to add 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev' to ALLOWED_HOSTS.
Bad Request: /
WARNING 2025-08-15 15:43:54,677 log 5390 140578927056576 Bad Request: /
[15/Aug/2025 15:43:54] "GET / HTTP/1.1" 400 171051